import Head from "next/head";
import Image from "next/image";
import { MainComponent } from "../src/components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Easybank landing page</title>
        <meta
          name="a web landing page"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainComponent />
    </>
  );
}
